#!/usr/bin/env python

import logging
import sys

from finder import find_region
from errors import UnknownAWSInstance

if __name__ == '__main__':
    logging.basicConfig(level=logging.CRITICAL)

    for id in sys.argv[1:]:
        try:
            print '%s:%s' % (id, find_region(id).name)
        except UnknownAWSInstance:
            print 'Unknown instance: %s' % id

